INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(100, 'Soundwave', 'D', 8, 9, 2, 6, 7, 5, 6, 10);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(101, 'Bluestreak', 'A', 6, 6, 7, 9, 5, 2, 9, 7);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(102, 'Hubcap', 'A', 4, 4, 4, 4, 4, 4, 4, 4);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(103, 'Optimus Prime', 'D', 5, 3, 7, 9, 10, 6, 1, 3);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(104, 'Megatron', 'D', 10, 5, 2, 8, 8, 7, 10, 2);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(105, 'Predaking', 'A', 2, 1, 2, 4, 1, 6, 3, 1);