INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(100, 'Soundwave', 'D', 8, 9, 2, 6, 7, 5, 6, 10);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(101, 'Bluestreak', 'A', 6, 6, 7, 9, 5, 2, 9, 7);
INSERT INTO
TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL)
VALUES(102, 'Hubcap', 'A', 4, 4, 4, 4, 4, 4, 4, 4);