INSERT INTO TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL, OVERALLRATING) VALUES(100, 'abc', 'A', 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO TRANSFORMER(ID, NAME, TEAM, STRENGTH, INTELLIGENCE, SPEED, ENDURANCE, RANK, COURAGE, FIREPOWER, SKILL, OVERALLRATING) VALUES(101, 'xyz', 'D', 2, 2, 2, 2, 2, 2, 2, 2, 2);
COMMIT;